version: "3"
 
services:
  apollo-configservice:
    container_name: apollo-configservice
    build: apollo-configservice/
    image: apollo-configservice:1.1.0
    ports:
      - "8080:8080"
    volumes:
      - "f:/opt/logs/100003171:/opt/logs/100003171" 
    environment:
      - spring_datasource_url=jdbc:mysql://192.168.3.116:3306/ApolloConfigDB?characterEncoding=utf8
      - spring_datasource_username=root
      - spring_datasource_password=root
 
  apollo-adminservice:
    container_name: apollo-adminservice
    build: apollo-adminservice/
    image: apollo-adminservice:1.1.0
    ports:
      - "8090:8090"
    depends_on:
      - apollo-configservice
    volumes:
      - "f:/opt/logs/100003172:/opt/logs/100003172"
    environment:
      - spring_datasource_url=jdbc:mysql://192.168.3.116:3306/ApolloConfigDB?characterEncoding=utf8
      - spring_datasource_username=root
      - spring_datasource_password=root
 
  apollo-portal:
    container_name: apollo-portal
    build: apollo-portal/
    image: apollo-portal:1.1.0
    ports:
      - "8070:8070"
    depends_on:
      - apollo-adminservice
    volumes:
      - "f:/opt/logs/100003173:/opt/logs/100003173"
    environment:
      - JAVA_OPTS="-Ddev_meta=http://192.168.3.113:8080"
      - spring_datasource_url=jdbc:mysql://192.168.3.116:3306/ApolloPortalDB?characterEncoding=utf8
      - spring_datasource_username=root
      - spring_datasource_password=root
